package com.sam.modules.dao;

import com.sam.modules.entity.Userinfo;
import com.sam.modules.entity.UserinfoExample;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Component;

public interface UserinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.userinfo
     *
     * @mbggenerated Thu Jun 11 13:10:13 CST 2015
     */
    @SelectProvider(type=UserinfoSqlProvider.class, method="countByExample")
    int countByExample(UserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.userinfo
     *
     * @mbggenerated Thu Jun 11 13:10:13 CST 2015
     */
    @DeleteProvider(type=UserinfoSqlProvider.class, method="deleteByExample")
    int deleteByExample(UserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.userinfo
     *
     * @mbggenerated Thu Jun 11 13:10:13 CST 2015
     */
    @Delete({
        "delete from \"public\".\"userinfo\"",
        "where \"serno\" = #{serno,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long serno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.userinfo
     *
     * @mbggenerated Thu Jun 11 13:10:13 CST 2015
     */
    @Insert({
        "insert into \"public\".\"userinfo\" (\"usertype\", \"userid\", ",
        "\"timecreate\")",
        "values (#{usertype,jdbcType=INTEGER}, #{userid,jdbcType=VARCHAR}, ",
        "#{timecreate,jdbcType=TIMESTAMP})"
    })
    @Options(useGeneratedKeys=true,keyProperty="serno")
    int insert(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.userinfo
     *
     * @mbggenerated Thu Jun 11 13:10:13 CST 2015
     */
    @InsertProvider(type=UserinfoSqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys=true,keyProperty="serno")
    int insertSelective(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.userinfo
     *
     * @mbggenerated Thu Jun 11 13:10:13 CST 2015
     */
    @SelectProvider(type=UserinfoSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="serno", property="serno", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="usertype", property="usertype", jdbcType=JdbcType.INTEGER),
        @Result(column="userid", property="userid", jdbcType=JdbcType.VARCHAR),
        @Result(column="timecreate", property="timecreate", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Userinfo> selectByExample(UserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.userinfo
     *
     * @mbggenerated Thu Jun 11 13:10:13 CST 2015
     */
    @Select({
        "select",
        "\"serno\", \"usertype\", \"userid\", \"timecreate\"",
        "from \"public\".\"userinfo\"",
        "where \"serno\" = #{serno,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="serno", property="serno", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="usertype", property="usertype", jdbcType=JdbcType.INTEGER),
        @Result(column="userid", property="userid", jdbcType=JdbcType.VARCHAR),
        @Result(column="timecreate", property="timecreate", jdbcType=JdbcType.TIMESTAMP)
    })
    Userinfo selectByPrimaryKey(Long serno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.userinfo
     *
     * @mbggenerated Thu Jun 11 13:10:13 CST 2015
     */
    @UpdateProvider(type=UserinfoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Userinfo record, @Param("example") UserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.userinfo
     *
     * @mbggenerated Thu Jun 11 13:10:13 CST 2015
     */
    @UpdateProvider(type=UserinfoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Userinfo record, @Param("example") UserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.userinfo
     *
     * @mbggenerated Thu Jun 11 13:10:13 CST 2015
     */
    @UpdateProvider(type=UserinfoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.userinfo
     *
     * @mbggenerated Thu Jun 11 13:10:13 CST 2015
     */
    @Update({
        "update \"public\".\"userinfo\"",
        "set \"usertype\" = #{usertype,jdbcType=INTEGER},",
          "\"userid\" = #{userid,jdbcType=VARCHAR},",
          "\"timecreate\" = #{timecreate,jdbcType=TIMESTAMP}",
        "where \"serno\" = #{serno,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Userinfo record);
}