package com.sam.modules.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.userinfo
     *
     * @mbggenerated Thu Jun 11 13:10:13 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.userinfo
     *
     * @mbggenerated Thu Jun 11 13:10:13 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.userinfo
     *
     * @mbggenerated Thu Jun 11 13:10:13 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.userinfo
     *
     * @mbggenerated Thu Jun 11 13:10:13 CST 2015
     */
    public UserinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.userinfo
     *
     * @mbggenerated Thu Jun 11 13:10:13 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.userinfo
     *
     * @mbggenerated Thu Jun 11 13:10:13 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.userinfo
     *
     * @mbggenerated Thu Jun 11 13:10:13 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.userinfo
     *
     * @mbggenerated Thu Jun 11 13:10:13 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.userinfo
     *
     * @mbggenerated Thu Jun 11 13:10:13 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.userinfo
     *
     * @mbggenerated Thu Jun 11 13:10:13 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.userinfo
     *
     * @mbggenerated Thu Jun 11 13:10:13 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.userinfo
     *
     * @mbggenerated Thu Jun 11 13:10:13 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.userinfo
     *
     * @mbggenerated Thu Jun 11 13:10:13 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.userinfo
     *
     * @mbggenerated Thu Jun 11 13:10:13 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.userinfo
     *
     * @mbggenerated Thu Jun 11 13:10:13 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSernoIsNull() {
            addCriterion("\"serno\" is null");
            return (Criteria) this;
        }

        public Criteria andSernoIsNotNull() {
            addCriterion("\"serno\" is not null");
            return (Criteria) this;
        }

        public Criteria andSernoEqualTo(Long value) {
            addCriterion("\"serno\" =", value, "serno");
            return (Criteria) this;
        }

        public Criteria andSernoNotEqualTo(Long value) {
            addCriterion("\"serno\" <>", value, "serno");
            return (Criteria) this;
        }

        public Criteria andSernoGreaterThan(Long value) {
            addCriterion("\"serno\" >", value, "serno");
            return (Criteria) this;
        }

        public Criteria andSernoGreaterThanOrEqualTo(Long value) {
            addCriterion("\"serno\" >=", value, "serno");
            return (Criteria) this;
        }

        public Criteria andSernoLessThan(Long value) {
            addCriterion("\"serno\" <", value, "serno");
            return (Criteria) this;
        }

        public Criteria andSernoLessThanOrEqualTo(Long value) {
            addCriterion("\"serno\" <=", value, "serno");
            return (Criteria) this;
        }

        public Criteria andSernoIn(List<Long> values) {
            addCriterion("\"serno\" in", values, "serno");
            return (Criteria) this;
        }

        public Criteria andSernoNotIn(List<Long> values) {
            addCriterion("\"serno\" not in", values, "serno");
            return (Criteria) this;
        }

        public Criteria andSernoBetween(Long value1, Long value2) {
            addCriterion("\"serno\" between", value1, value2, "serno");
            return (Criteria) this;
        }

        public Criteria andSernoNotBetween(Long value1, Long value2) {
            addCriterion("\"serno\" not between", value1, value2, "serno");
            return (Criteria) this;
        }

        public Criteria andUsertypeIsNull() {
            addCriterion("\"usertype\" is null");
            return (Criteria) this;
        }

        public Criteria andUsertypeIsNotNull() {
            addCriterion("\"usertype\" is not null");
            return (Criteria) this;
        }

        public Criteria andUsertypeEqualTo(Integer value) {
            addCriterion("\"usertype\" =", value, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeNotEqualTo(Integer value) {
            addCriterion("\"usertype\" <>", value, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeGreaterThan(Integer value) {
            addCriterion("\"usertype\" >", value, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"usertype\" >=", value, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeLessThan(Integer value) {
            addCriterion("\"usertype\" <", value, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeLessThanOrEqualTo(Integer value) {
            addCriterion("\"usertype\" <=", value, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeIn(List<Integer> values) {
            addCriterion("\"usertype\" in", values, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeNotIn(List<Integer> values) {
            addCriterion("\"usertype\" not in", values, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeBetween(Integer value1, Integer value2) {
            addCriterion("\"usertype\" between", value1, value2, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeNotBetween(Integer value1, Integer value2) {
            addCriterion("\"usertype\" not between", value1, value2, "usertype");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("\"userid\" is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("\"userid\" is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(String value) {
            addCriterion("\"userid\" =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(String value) {
            addCriterion("\"userid\" <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(String value) {
            addCriterion("\"userid\" >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(String value) {
            addCriterion("\"userid\" >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(String value) {
            addCriterion("\"userid\" <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(String value) {
            addCriterion("\"userid\" <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLike(String value) {
            addCriterion("\"userid\" like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotLike(String value) {
            addCriterion("\"userid\" not like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<String> values) {
            addCriterion("\"userid\" in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<String> values) {
            addCriterion("\"userid\" not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(String value1, String value2) {
            addCriterion("\"userid\" between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(String value1, String value2) {
            addCriterion("\"userid\" not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andTimecreateIsNull() {
            addCriterion("\"timecreate\" is null");
            return (Criteria) this;
        }

        public Criteria andTimecreateIsNotNull() {
            addCriterion("\"timecreate\" is not null");
            return (Criteria) this;
        }

        public Criteria andTimecreateEqualTo(Date value) {
            addCriterion("\"timecreate\" =", value, "timecreate");
            return (Criteria) this;
        }

        public Criteria andTimecreateNotEqualTo(Date value) {
            addCriterion("\"timecreate\" <>", value, "timecreate");
            return (Criteria) this;
        }

        public Criteria andTimecreateGreaterThan(Date value) {
            addCriterion("\"timecreate\" >", value, "timecreate");
            return (Criteria) this;
        }

        public Criteria andTimecreateGreaterThanOrEqualTo(Date value) {
            addCriterion("\"timecreate\" >=", value, "timecreate");
            return (Criteria) this;
        }

        public Criteria andTimecreateLessThan(Date value) {
            addCriterion("\"timecreate\" <", value, "timecreate");
            return (Criteria) this;
        }

        public Criteria andTimecreateLessThanOrEqualTo(Date value) {
            addCriterion("\"timecreate\" <=", value, "timecreate");
            return (Criteria) this;
        }

        public Criteria andTimecreateIn(List<Date> values) {
            addCriterion("\"timecreate\" in", values, "timecreate");
            return (Criteria) this;
        }

        public Criteria andTimecreateNotIn(List<Date> values) {
            addCriterion("\"timecreate\" not in", values, "timecreate");
            return (Criteria) this;
        }

        public Criteria andTimecreateBetween(Date value1, Date value2) {
            addCriterion("\"timecreate\" between", value1, value2, "timecreate");
            return (Criteria) this;
        }

        public Criteria andTimecreateNotBetween(Date value1, Date value2) {
            addCriterion("\"timecreate\" not between", value1, value2, "timecreate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.userinfo
     *
     * @mbggenerated do_not_delete_during_merge Thu Jun 11 13:10:13 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.userinfo
     *
     * @mbggenerated Thu Jun 11 13:10:13 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}